# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.9

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/linshenqi/tools/clion-2017.2.3/bin/cmake/bin/cmake

# The command to remove a file.
RM = /home/linshenqi/tools/clion-2017.2.3/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/linshenqi/empower/iotseed-sdks-core

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/linshenqi/empower/iotseed-sdks-core

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/linshenqi/tools/clion-2017.2.3/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/linshenqi/tools/clion-2017.2.3/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/linshenqi/empower/iotseed-sdks-core/CMakeFiles /home/linshenqi/empower/iotseed-sdks-core/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/linshenqi/empower/iotseed-sdks-core/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named iotseed_sdks_core

# Build rule for target.
iotseed_sdks_core: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 iotseed_sdks_core
.PHONY : iotseed_sdks_core

# fast build rule for target.
iotseed_sdks_core/fast:
	$(MAKE) -f CMakeFiles/iotseed_sdks_core.dir/build.make CMakeFiles/iotseed_sdks_core.dir/build
.PHONY : iotseed_sdks_core/fast

lib/mongoose/mongoose.o: lib/mongoose/mongoose.c.o

.PHONY : lib/mongoose/mongoose.o

# target to build an object file
lib/mongoose/mongoose.c.o:
	$(MAKE) -f CMakeFiles/iotseed_sdks_core.dir/build.make CMakeFiles/iotseed_sdks_core.dir/lib/mongoose/mongoose.c.o
.PHONY : lib/mongoose/mongoose.c.o

lib/mongoose/mongoose.i: lib/mongoose/mongoose.c.i

.PHONY : lib/mongoose/mongoose.i

# target to preprocess a source file
lib/mongoose/mongoose.c.i:
	$(MAKE) -f CMakeFiles/iotseed_sdks_core.dir/build.make CMakeFiles/iotseed_sdks_core.dir/lib/mongoose/mongoose.c.i
.PHONY : lib/mongoose/mongoose.c.i

lib/mongoose/mongoose.s: lib/mongoose/mongoose.c.s

.PHONY : lib/mongoose/mongoose.s

# target to generate assembly for a file
lib/mongoose/mongoose.c.s:
	$(MAKE) -f CMakeFiles/iotseed_sdks_core.dir/build.make CMakeFiles/iotseed_sdks_core.dir/lib/mongoose/mongoose.c.s
.PHONY : lib/mongoose/mongoose.c.s

src/jsonrpc.o: src/jsonrpc.cpp.o

.PHONY : src/jsonrpc.o

# target to build an object file
src/jsonrpc.cpp.o:
	$(MAKE) -f CMakeFiles/iotseed_sdks_core.dir/build.make CMakeFiles/iotseed_sdks_core.dir/src/jsonrpc.cpp.o
.PHONY : src/jsonrpc.cpp.o

src/jsonrpc.i: src/jsonrpc.cpp.i

.PHONY : src/jsonrpc.i

# target to preprocess a source file
src/jsonrpc.cpp.i:
	$(MAKE) -f CMakeFiles/iotseed_sdks_core.dir/build.make CMakeFiles/iotseed_sdks_core.dir/src/jsonrpc.cpp.i
.PHONY : src/jsonrpc.cpp.i

src/jsonrpc.s: src/jsonrpc.cpp.s

.PHONY : src/jsonrpc.s

# target to generate assembly for a file
src/jsonrpc.cpp.s:
	$(MAKE) -f CMakeFiles/iotseed_sdks_core.dir/build.make CMakeFiles/iotseed_sdks_core.dir/src/jsonrpc.cpp.s
.PHONY : src/jsonrpc.cpp.s

src/log.o: src/log.cpp.o

.PHONY : src/log.o

# target to build an object file
src/log.cpp.o:
	$(MAKE) -f CMakeFiles/iotseed_sdks_core.dir/build.make CMakeFiles/iotseed_sdks_core.dir/src/log.cpp.o
.PHONY : src/log.cpp.o

src/log.i: src/log.cpp.i

.PHONY : src/log.i

# target to preprocess a source file
src/log.cpp.i:
	$(MAKE) -f CMakeFiles/iotseed_sdks_core.dir/build.make CMakeFiles/iotseed_sdks_core.dir/src/log.cpp.i
.PHONY : src/log.cpp.i

src/log.s: src/log.cpp.s

.PHONY : src/log.s

# target to generate assembly for a file
src/log.cpp.s:
	$(MAKE) -f CMakeFiles/iotseed_sdks_core.dir/build.make CMakeFiles/iotseed_sdks_core.dir/src/log.cpp.s
.PHONY : src/log.cpp.s

src/mqtt.o: src/mqtt.cpp.o

.PHONY : src/mqtt.o

# target to build an object file
src/mqtt.cpp.o:
	$(MAKE) -f CMakeFiles/iotseed_sdks_core.dir/build.make CMakeFiles/iotseed_sdks_core.dir/src/mqtt.cpp.o
.PHONY : src/mqtt.cpp.o

src/mqtt.i: src/mqtt.cpp.i

.PHONY : src/mqtt.i

# target to preprocess a source file
src/mqtt.cpp.i:
	$(MAKE) -f CMakeFiles/iotseed_sdks_core.dir/build.make CMakeFiles/iotseed_sdks_core.dir/src/mqtt.cpp.i
.PHONY : src/mqtt.cpp.i

src/mqtt.s: src/mqtt.cpp.s

.PHONY : src/mqtt.s

# target to generate assembly for a file
src/mqtt.cpp.s:
	$(MAKE) -f CMakeFiles/iotseed_sdks_core.dir/build.make CMakeFiles/iotseed_sdks_core.dir/src/mqtt.cpp.s
.PHONY : src/mqtt.cpp.s

src/operation_utils.o: src/operation_utils.cpp.o

.PHONY : src/operation_utils.o

# target to build an object file
src/operation_utils.cpp.o:
	$(MAKE) -f CMakeFiles/iotseed_sdks_core.dir/build.make CMakeFiles/iotseed_sdks_core.dir/src/operation_utils.cpp.o
.PHONY : src/operation_utils.cpp.o

src/operation_utils.i: src/operation_utils.cpp.i

.PHONY : src/operation_utils.i

# target to preprocess a source file
src/operation_utils.cpp.i:
	$(MAKE) -f CMakeFiles/iotseed_sdks_core.dir/build.make CMakeFiles/iotseed_sdks_core.dir/src/operation_utils.cpp.i
.PHONY : src/operation_utils.cpp.i

src/operation_utils.s: src/operation_utils.cpp.s

.PHONY : src/operation_utils.s

# target to generate assembly for a file
src/operation_utils.cpp.s:
	$(MAKE) -f CMakeFiles/iotseed_sdks_core.dir/build.make CMakeFiles/iotseed_sdks_core.dir/src/operation_utils.cpp.s
.PHONY : src/operation_utils.cpp.s

src/recipe.o: src/recipe.cpp.o

.PHONY : src/recipe.o

# target to build an object file
src/recipe.cpp.o:
	$(MAKE) -f CMakeFiles/iotseed_sdks_core.dir/build.make CMakeFiles/iotseed_sdks_core.dir/src/recipe.cpp.o
.PHONY : src/recipe.cpp.o

src/recipe.i: src/recipe.cpp.i

.PHONY : src/recipe.i

# target to preprocess a source file
src/recipe.cpp.i:
	$(MAKE) -f CMakeFiles/iotseed_sdks_core.dir/build.make CMakeFiles/iotseed_sdks_core.dir/src/recipe.cpp.i
.PHONY : src/recipe.cpp.i

src/recipe.s: src/recipe.cpp.s

.PHONY : src/recipe.s

# target to generate assembly for a file
src/recipe.cpp.s:
	$(MAKE) -f CMakeFiles/iotseed_sdks_core.dir/build.make CMakeFiles/iotseed_sdks_core.dir/src/recipe.cpp.s
.PHONY : src/recipe.cpp.s

src/str_utils.o: src/str_utils.cpp.o

.PHONY : src/str_utils.o

# target to build an object file
src/str_utils.cpp.o:
	$(MAKE) -f CMakeFiles/iotseed_sdks_core.dir/build.make CMakeFiles/iotseed_sdks_core.dir/src/str_utils.cpp.o
.PHONY : src/str_utils.cpp.o

src/str_utils.i: src/str_utils.cpp.i

.PHONY : src/str_utils.i

# target to preprocess a source file
src/str_utils.cpp.i:
	$(MAKE) -f CMakeFiles/iotseed_sdks_core.dir/build.make CMakeFiles/iotseed_sdks_core.dir/src/str_utils.cpp.i
.PHONY : src/str_utils.cpp.i

src/str_utils.s: src/str_utils.cpp.s

.PHONY : src/str_utils.s

# target to generate assembly for a file
src/str_utils.cpp.s:
	$(MAKE) -f CMakeFiles/iotseed_sdks_core.dir/build.make CMakeFiles/iotseed_sdks_core.dir/src/str_utils.cpp.s
.PHONY : src/str_utils.cpp.s

src/time_utils.o: src/time_utils.cpp.o

.PHONY : src/time_utils.o

# target to build an object file
src/time_utils.cpp.o:
	$(MAKE) -f CMakeFiles/iotseed_sdks_core.dir/build.make CMakeFiles/iotseed_sdks_core.dir/src/time_utils.cpp.o
.PHONY : src/time_utils.cpp.o

src/time_utils.i: src/time_utils.cpp.i

.PHONY : src/time_utils.i

# target to preprocess a source file
src/time_utils.cpp.i:
	$(MAKE) -f CMakeFiles/iotseed_sdks_core.dir/build.make CMakeFiles/iotseed_sdks_core.dir/src/time_utils.cpp.i
.PHONY : src/time_utils.cpp.i

src/time_utils.s: src/time_utils.cpp.s

.PHONY : src/time_utils.s

# target to generate assembly for a file
src/time_utils.cpp.s:
	$(MAKE) -f CMakeFiles/iotseed_sdks_core.dir/build.make CMakeFiles/iotseed_sdks_core.dir/src/time_utils.cpp.s
.PHONY : src/time_utils.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... iotseed_sdks_core"
	@echo "... lib/mongoose/mongoose.o"
	@echo "... lib/mongoose/mongoose.i"
	@echo "... lib/mongoose/mongoose.s"
	@echo "... src/jsonrpc.o"
	@echo "... src/jsonrpc.i"
	@echo "... src/jsonrpc.s"
	@echo "... src/log.o"
	@echo "... src/log.i"
	@echo "... src/log.s"
	@echo "... src/mqtt.o"
	@echo "... src/mqtt.i"
	@echo "... src/mqtt.s"
	@echo "... src/operation_utils.o"
	@echo "... src/operation_utils.i"
	@echo "... src/operation_utils.s"
	@echo "... src/recipe.o"
	@echo "... src/recipe.i"
	@echo "... src/recipe.s"
	@echo "... src/str_utils.o"
	@echo "... src/str_utils.i"
	@echo "... src/str_utils.s"
	@echo "... src/time_utils.o"
	@echo "... src/time_utils.i"
	@echo "... src/time_utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

